data:
  data_dir: "data/100tasks50scenarios"
  train_file: "train.jld2"
  validation_file: "validation.jld2"
train:
  log_dir: "logs"
  tag: "imitation_100tasks50scenarios"
  batchsize: 1
  metrics:
    train_and_validation:
      - "Loss"
      - "AllCosts"
    train:
    validation:
  optimizer:
    name: "ADAM"
    args:
  nb_epochs: 50
  save_every_n_epochs: 50
  log_every_n_epochs: 1
model:
  name: "FenchelYoungGLM"
  args:
    M: 20
    nb_features: 20
    Îµ: 0.1
    model_builder: "grb_model"
