train:
  batchsize: 1
  save_every_n_epochs: 1000
  metrics:
    test: ~
    train:
      - "ModelWeights"
    train_and_test:
      - "Loss"
      - "AverageCostGap"
      - "MaxCostGap"
      - "AveragePerturbedCostGap"
  tag: "test_new_inferopt_normalized"
  optimizer:
    name: "ADAM"
    args: ~
  nb_epochs: 10000
  log_dir: "logs"
  log_every_n_epochs: 100
model:
  name: "PerturbedGLM"
  args:
    M: 5
    nb_features: 20
    Îµ: 250
    model_builder: "grb_model"
data:
  data_dir: "data/data50_normalized"
  test_file: "test.jld2"
  train_file: "train.jld2"
