experiment_name: experiment
log_dir: logs
data:
  data_dir: data/data50
  train_file: train.jld2
  test_file: test.jld2
training:
  nb_epochs: 100
  optimizer:
    name: ADAM
    args:
      Î·: 0.65
  metrics:
    - Loss
    - CostGap
