data:
  data_dir: "/libre/batyl/data/StoVSP/100tasks50scenarios"
  train_file: "train.jld2"
  validation_file: "validation.jld2"
train:
  log_dir: "logs"
  tag: "experience_100tasks50scenarios"
  batchsize: 1
  metrics:
    train_and_validation:
      - "Loss"
      - "AvgCostPerTask"
    train:
    validation:
  optimizer:
    name: "Adam"
    args:
  nb_epochs: 200
  save_every_n_epochs: 100
  log_every_n_epochs: 10
model:
  name: "PerturbedGLM"
  args:
    M: 20
    nb_features: 20
    ε: 15
    model_builder: "grb_model"
