data:
  data_dir: "data/100tasks50scenarios"
  train_file: "train.jld2"
  validation_file: "validation.jld2"
train:
  log_dir: "logs"
  tag: "experience_100tasks50scenariosDescent"
  batchsize: 1
  metrics:
    train_and_validation:
      - "Loss"
      - "AllCosts"
    train:
    validation:
  optimizer:
    name: "Descent(1e-6)"
    args:
  nb_epochs: 200
  save_every_n_epochs: 100
  log_every_n_epochs: 10
model:
  name: "PerturbedGLM"
  args:
    M: 20
    nb_features: 20
    Îµ: 300
    model_builder: "grb_model"
