data:
  data_dir: "data/mixed_uncentered"
  train_file: "train.jld2"
  validation_file: "validation.jld2"
train:
  log_dir: "final_experiments"
  tag: "experience_mixed"
  batchsize: 1
  metrics:
    train_and_validation:
      - "Loss"
      - "AllCosts"
    train:
    validation:
  optimizer:
    name: "ADAM"
    args:
  nb_epochs: 200
  save_every_n_epochs: 200
  log_every_n_epochs: 1
model:
  name: "PerturbedGLM"
  args:
    M: 20
    nb_features: 20
    Îµ: 300
    model_builder: "grb_model"
